---
title: "Homework_6"
author: "Emmenta Janneh"
date: "2024-03-07"
output: pdf_document
---

```{r}
library(tidyverse)
library(broom)
```

## Loans

## 1

```{r}
y <- c(16, 5, 10, 15, 13, 22)
y
```

## 2

```{r}
x <- matrix(c(1, 4,
              1, 1, 
              1, 2, 
              1, 3, 
              1, 3, 
              1, 4), nrow = 6, ncol = 2, byrow = TRUE)
x
```

## 3

```{r}
batahat <- solve(t(x) %*% x) %*% t(x) %*% y
batahat
```

## 4

```{r}
yhat <- x %*% batahat
resid <- y - yhat

MSE <- mean(resid^2)
MSE
```

## 5

```{r}
SEbetahat <- sqrt(diag(MSE * solve(t(x) %*% x)))
SEbetahat
```

## 6

```{r}
lmloan <- lm(y ~ x[, 2])
tidy(lmloan)
```

## Other Questions

## 1

$$ \mathbf{W} = \begin{bmatrix} 1 & -1 & 2 \\ 0 & 1 & -1 \\ 1 & 0 & 0 \end{bmatrix} \begin{bmatrix} Y_1 \\ Y_2 \\ Y_3 \end{bmatrix} $$
## 2

```{r}
A <- matrix(c(1, 3, 5,
              2, 4, 6), nrow = 2, ncol = 3, byrow = TRUE)

B <- matrix(c(2, -2,
              1,  -1,
              3, -3), nrow = 3, ncol = 2, byrow = TRUE)

A %*% B
```

